[package]
name = "voxelengine"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["bin/*"]
resolver = "2"

[workspace.dependencies]
bevy = "0.18.1"
bevy_mod_scripting_lua = { version = "0.19.0", features = ["lua54"] }



[profile.dev]
opt-level = 1 # faster builds, decent perf in dev

[profile.dev.package."*"]
opt-level = 3 # optimize dependencies even in dev

[profile.release]
opt-level = 3
lto = "thin"
